"""Compute IR between the Graph and Loop IRs."""

from __future__ import annotations

from .axis import Axis, AxisKind
from .index import (
    AxisRef,
    CompareOp,
    IndexAdd,
    IndexCompare,
    IndexExpr,
    IndexFloorDiv,
    IndexMod,
    IndexMul,
    IntConst,
    as_index,
    index_axes,
    index_eq,
    index_ge,
    index_gt,
    index_le,
    index_lt,
    index_ne,
)
from .program import (
    Combiner,
    ComputeBlock,
    ComputeProgram,
    ComputeProgramBuilder,
    ComputeTensor,
    DenseConst,
)
from .scalar import (
    Read,
    ScalarAdd,
    ScalarConst,
    ScalarDiv,
    ScalarExp,
    ScalarExpr,
    ScalarExprBase,
    ScalarLog,
    ScalarMax,
    ScalarMul,
    ScalarNeg,
    ScalarOpKind,
    ScalarPow,
    ScalarSub,
    ScalarTanh,
    Select,
)
from .transform import ComputeProgramTransform, apply_transforms
from .verify import VerifyError, verify_block, verify_program

__all__ = [
    "ComputeProgramTransform",
    "apply_transforms",
    "Axis",
    "AxisKind",
    "IndexExpr",
    "AxisRef",
    "IntConst",
    "IndexAdd",
    "IndexMul",
    "IndexFloorDiv",
    "IndexMod",
    "IndexCompare",
    "CompareOp",
    "index_lt",
    "index_le",
    "index_gt",
    "index_ge",
    "index_eq",
    "index_ne",
    "index_axes",
    "as_index",
    "ScalarOpKind",
    "ScalarExprBase",
    "ScalarConst",
    "ScalarExpr",
    "ScalarAdd",
    "ScalarSub",
    "ScalarMul",
    "ScalarDiv",
    "ScalarNeg",
    "ScalarExp",
    "ScalarLog",
    "ScalarTanh",
    "ScalarMax",
    "ScalarPow",
    "ComputeTensor",
    "Combiner",
    "ComputeBlock",
    "ComputeProgram",
    "ComputeProgramBuilder",
    "DenseConst",
    "Read",
    "Select",
    "VerifyError",
    "verify_block",
    "verify_program",
]
